# Generated by Django 3.1.7 on 2021-03-05 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('product', models.CharField(max_length=155)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('offer_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('detail', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(blank=True, default=0, null=True)),
                ('shop_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.shopdetail')),
            ],
        ),
    ]
