# Generated by Django 3.1.7 on 2021-03-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
